### PR TITLE
Remove bad args and only return IP addresses when setting up UFW for …

### PR DESCRIPTION
**Pull request by rhartkopf**
…sensors

### CODE REVIEW

**Comment by rhartkopf** [comment]
I ran into multiple issues with the current configuration. The biggest issue was that IP address display is not forced on 'who', so hostnames are sometimes assigned to $IPADDRESS, which breaks the UFW command.

Another issue occurs when there are multiple SSH sessions on the server. 'who' returns one line per SSH session, which returns a multi-line $IPADDRESS variable. This also breaks the UFW command.

**Comment by dougburks** [comment]
Thanks, @rhartkopf !

I've created an Issue to track this:
https://github.com/Security-Onion-Solutions/security-onion/issues/891

**Comment by dougburks** [comment]
What happens if $SUDO_USER is logged in multiple times?

Instead of doing `who --ips | grep $SUDO_USER` could/should we do `who -m --ips` to target that individual SSH session?

**Comment by rhartkopf** [comment]
Good catch! Changes pushed.

**Comment by dougburks** [comment]
Looks like your new pull request has the "-q" option.  Is this intentional?  Should that be "-m" instead?

**Comment by rhartkopf** [comment]
Fixed

**Pull request merged**
