### PR TITLE
Security Onion Email Setup

### PR DESCRIPTION
**Pull request by weslambert**
Provides the ability to automatically configure email for:

- Daily sostat output
- Bro
- Sguil
- OSSEC
- ELSA

Currently works as GUI/Zenity dialog.  I plan to add CLI/answer file, logging, similar to that of sosetup.
Installs mailutils/nullmailer if not currently installed.

Thanks,
Wes

### CODE REVIEW

**Comment by dougburks** [comment]
Very nice, Wes, thanks!

I seem to remember some folks having issues with Sguil sending email if their corporate mail server requires TLS (due to the tcl SMTP libraries having sub-optimal TLS support).  I wonder if we should configure Sguil to relay through nullmailer to try to avoid this issue.  I also then wonder if we should configure all services to relay through nullmailer to avoid any potential future issues and ensure consistency.

Thoughts?

Thanks!

**Comment by weslambert** [comment]
Ah, yes, I remember seeing that..

Ex.
https://groups.google.com/forum/#!searchin/security-onion/sguil$20tls%7Csort:date/security-onion/5NNczv4EUhk/wW7iOEBKAQAJ


I think relaying all mail from the services through nullmailer would a
great idea, especially from a management/maintenance standpoint--I'll
definitely look into it.

Thanks for the suggestion!


Thanks,
Wes

**Comment by dougburks** [comment]
Thanks, Wes!

**Comment by dougburks** [comment]
Thanks, Wes!  I'll try to take a look next week.

**Comment by weslambert** [comment]
So, I ending up re-writing the script to relay all mail through Postifx.  All of the applications send mail to root, and the mail is forwarded to the SMTP server defined in /etc/postfix/main.cf and to the appropriate destination address defined in /etc/aliases.  

Users can test via the following:

**OSSEC alert emails** should be generated whenever the script finishes running
**Sguil alert emails** can be generated through the replay of traffic via tcpreplay:

 Ex. sudo tcpreplay -i eth1 -M10 /opt/samples/*

**ELSA alert emails** can be tested by creating an alert/schedule within ELSA for a particular alert that occurs normally, or that is generated through the tcpreplay command above.

**Bro alert emails** can be tested by rebooting the machine and looking for the Bro "crash" emails.

**sostat emails** can be tested by changing the job interval for sostat emails in /etc/cron.d/sostat from:
 '0 12 * * *' to '* * * * *'

Thanks,
Wes

**Comment by dougburks** [comment]
Nice testing guidelines, thanks!

**Comment by dougburks** [comment]
Should it install Postfix if not already installed?

**Comment by weslambert** [comment]
Yes, it installs Postfix as part of the mailutils package.

Thanks,
Wes

**Comment by dougburks** [comment]
I haven't looked at this too closely, so please correct me if I'm wrong.  Postfix should be a separate package from mailutils.  The mailutils installation may `recommend` Postfix which may install it if no other MTA is found.  I'm thinking that if a user has some other MTA installed already then this wouldn't install Postfix.  It may be worth adding a check to see if Postfix is installed and, if not, install it.

**Comment by weslambert** [comment]
You, are correct sir!  I just tested with nullmailer installed first, and
mailutils used that as the MTA (and did not install Postfix), so I will add
a check as you recommended.

Oh, and Happy Father's Day!

Thanks,
Wes

Yes, it installs Postfix as part of the mailutils package.

Thanks,
Wes

**Comment by dougburks** [comment]
Thanks, Wes!

**Comment by dougburks** [comment]
Looks like it's starting to come together.  Thanks for your continued work, Wes!

**Comment by weslambert** [comment]
Thanks, Doug!

**Pull request merged**
