### PR TITLE
Add -w option to sosetup for generating an answer file

### PR DESCRIPTION
**Pull request by petiepooo**
This patch enables a -w <file> option to sosetup that generates a new
answerfile that can then be fed into sosetup with the -f <file> option.
It specifically does not support sosetup-network, and warns the user
that the network must be configured before running it with the answer
file it generates.  It does support running in generate mode as a non-
root user.

### CODE REVIEW

**Comment by petiepooo** [comment]
Doug, I figured out how to update an existing pull request.  Easy as adding another commit to the branch I requested be pulled.  This should be a working change now with these two commits.

**Comment by dougburks** [comment]
Thanks, Pete!

**Comment by petiepooo** [comment]
Updated to reflect the removal of snorby..  any issues with this I can address to help get this merged?

**Comment by dougburks** [comment]
I haven't had time to look at this since I was focused on BDR2.  Will try to take a look at it soon.  Thanks!

**Pull request merged**
